# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MS SQL Server 2022 Express
theme: just-the-docs
description: >- # this means to ignore newlines until "baseurl:"
  SQL Server 2019 Express on Google Cloud Platform!

baseurl: "/SQL-Server-2022-Express" # the subpath of your site, e.g. /blog
url: "https://gclouds-co-uk.github.io/SQL-Server-2022-Express" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gclouds2
github_username:
email: support@gclouds.co.uk
markdown: kramdown
# Build settings
# theme: minima
plugins:
  - jekyll-feed

aux_links:
  "gClouds Home":
    - "//www.gclouds.co.uk"
aux_links_new_tab: true

heading_anchors: true
enable_copy_code_button: true
nav_enabled: true

logo: "/assets/images/gclouds.png"
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.9.1"

footer_content: "Copyright © 2024  |  <a href='https://www.gclouds.co.uk'>gClouds</a> . All rights reserved."

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
